### ISSUE TITLE
Can the READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions be removed?

### ISSUE THREAD

**Issue by arnosolo** [capacitor-community/media#100]
As of today (October 24, 2024), removing these permissions will prevent photos from saving correctly on Android 13. Is there a way to remove them without causing this issue?

Why should these permissions be removed? Starting October 31, 2024, Google Play requires developers to submit declaration forms justifying the need for `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO `permissions, as outlined in their [Photo and Video Permissions policy](https://support.google.com/googleplay/android-developer/answer/14115180).

**Comment by nkalupahana** [comment]
Yep, I'm planning on fixing this and putting out a release this weekend. Sorry for the delay -- if you have an app out on Google Play, I recommend requesting a deadline extension.

**Comment by nkalupahana** [comment]
v7.0.0 has been released.

**Comment by nkalupahana** [comment]
FYI for anyone who ends up here: Google Play just announced that policy enforcement has been delayed to January 22, 2025 (with extensions available to May 28, 2025).

**Comment by alextreppass** [comment]
Thanks for addressing this.

Is v7 compatible with Capacitor v6? Asking as Capacitor v7 isn't fully launched yet

**Comment by nkalupahana** [comment]
Yes, v7 of the plugin is for Capacitor 6. The fact that the versions lined up before was a coincidence -- the README specifies the Capacitor version compatibility.
