### ISSUE TITLE
Unable to save photo on Android platform

### ISSUE THREAD

**Issue by sunmeng666** [capacitor-community/media#16]
it is always has error: ![image](https://user-images.githubusercontent.com/31534088/116370342-e1849a00-a83c-11eb-8020-3f8f79906643.png)
there are params:
![image](https://user-images.githubusercontent.com/31534088/116370561-1abd0a00-a83d-11eb-8e04-bcf1c57c1c30.png)

**Comment by stewones** [comment]
can you have a try on v3 and lemme know?
thank you
