### ISSUE TITLE
Plugin breaks on @capacitor/core@^3.0.0

### ISSUE THREAD

**Issue by brymartinez** [capacitor-community/media#17]
**Describe the bug**
Because the plugin pulls @capacitor/core@latest, it is now breaking on 3.0.0 because of this:
```
@deprecated
Plugins should be imported instead. Deprecated in v3 and Capacitor.Plugins property definition will not be exported in v4.
```

Problems are reported on `ionic serve`:

```
[ng] Error: node_modules/@capacitor-community/media/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
[ng]   Types of property 'Plugins' are incompatible.
[ng]     Property 'MediaPlugin' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.
[ng] 16 export interface CapacitorInstance extends CapacitorGlobal {
[ng]                     ~~~~~~~~~~~~~~~~~
[ng]   node_modules/@capacitor-community/media/dist/esm/definitions.d.ts:3:9
[ng]     3         MediaPlugin: MediaPluginProtocol;
[ng]               ~~~~~~~~~~~
[ng]     'MediaPlugin' is declared here.
[ng] Error: node_modules/@capacitor/filesystem/dist/esm/definitions.d.ts:1:15 - error TS2724: Module '"../../../core/dist/esm"' has no exported member 'PermissionState'. Did you mean 'PermissionType'?
[ng] 1 import type { PermissionState } from '@capacitor/core';
[ng]                 ~~~~~~~~~~~~~~~
[ng]   node_modules/@capacitor/core/dist/esm/core-plugin-definitions.d.ts:1243:21
[ng]     1243 export declare enum PermissionType {
[ng]                              ~~~~~~~~~~~~~~
[ng]     'PermissionType' is declared here.
[ng] Error: ./node_modules/@capacitor/filesystem/dist/esm/index.js 2:19-33
[ng] "export 'registerPlugin' was not found in '@capacitor/core'
```

**To Reproduce**
`npm install @capacitor-community/media`

**Expected behavior**
Working.

**Screenshots**

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
any 

**Additional context**

**Comment by tallesventura** [comment]
I've created a PR (#18) setting the required capacitor version to v2 while v3 is not supported.

**Comment by calls9-mattwyld** [comment]
Hi, will this be updated to support v3? 

My quick fix at the moment is to move it up to support v12.1 in xcode, but not sure what effect this will have, if any.
![image](https://user-images.githubusercontent.com/63339637/126160533-831da079-2bf7-471f-949b-eabb33d0266c.png)

**Comment by crawft** [comment]
+1, and btw - the guide for migrating to Capacitor 3 recommends using this plugin :/

**Comment by roxteddy** [comment]
> Hi, will this be updated to support v3?
> 
> My quick fix at the moment is to move it up to support v12.1 in xcode, but not sure what effect this will have, if any.
> ![image](https://user-images.githubusercontent.com/63339637/126160533-831da079-2bf7-471f-949b-eabb33d0266c.png)

@calls9-mattwyld ok but how do you deal with the TS errors ?

**Comment by philipjbrowning** [comment]
Setting the version to 2.4.7 will only work for iOS. Android requires another fix to get the folders to work b/c the DISTINCT query is not allowed anymore.

**Comment by stewones** [comment]
please have a try on v3
thank you
