### ISSUE TITLE
Permission in ios

### ISSUE THREAD

**Issue by Ibni-Amin** [capacitor-community/media#29]
If permission has just only for selected Photos then It create album but not return in getAlbums
and that's so on when I save another photo and it create every time new album

**Comment by nkalupahana** [comment]
Unfortunately, this is how the iOS permissions structure works. If only selected images permissions are given, non-default albums don't show up with `getAlbums`, and if you try to save to a specific album, it makes a new one. Even apps like Instagram have this issue -- I just checked my phone, and I have around 10 albums marked "Instagram", each with one image. If they have this issue, I doubt there's any way we can get around it.
