### ISSUE TITLE
npm install failing - not working in capacitor v4

### ISSUE THREAD

**Issue by mjaga** [capacitor-community/media#33]
after upgrading from v3 to v4
ionic : 4
angular : 11
 error: npm ERR! While resolving: @capacitor-community/media@3.0.0
npm ERR! Found: @capacitor/core@4.6.1

**Comment by nkalupahana** [comment]
Try running `npm install @capacitor-community/media@4.0.0-0` instead -- that should work!

**Comment by nkalupahana** [comment]
I just upgraded the package, so the normal `npm install` should now also work.
