### ISSUE TITLE
savePhoto fails with RuntimeException occurred in v4.0.1

### ISSUE THREAD

**Issue by macsupport** [capacitor-community/media#35]
**Describe the bug**
Camera Opens, Photo successful, then error on `savePhoto()`

**To Reproduce**
```js
function scanDocument2() {
  var image = document.getElementById("myImage").src;
return Capacitor.Plugins.DocumentScanner.scanDocument({
responseType: 'imageFilePath'
}).then(function(result) {
const scannedImages = result.scannedImages;
if (scannedImages.length > 0) {
const scannedImage = document.getElementById('myImage');
if (scannedImage) {
scannedImage.src = Capacitor.convertFileSrc(scannedImages[0]);
console.log(scannedImage.src)
// scannedImage.src = JSON.stringify("data:image/jpeg;base64," + scannedImages[0]);

localStorage.setItem("imageSrc", scannedImage.src);
setTimeout(function() {


 Capacitor.Plugins.Media
        .savePhoto({
          path: scannedImage.src,
          album: "Pictures",
        })
        .then((r) => console.log(r))
        .catch((e) => console.error(e));
     

}, 2500);
}
}
});
}
```

**Expected behavior**
Photo should be saved to device

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 

**Smartphone (please complete the following information):**
 - Device: Android Simulator
 - Version API 33

Stacktrace:

savePhotoV/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 55940831, pluginId: Media, methodName: savePhoto
V/Capacitor: callback: 55940831, pluginId: Media, methodName: savePhoto, methodData: {"path":"http:\/\/localhost\/_capacitor_file_\/storage\/emulated\/0\/Android\/data\/com.vetcalculators.sofie\/files\/Pictures\/DOCUMENT_SCAN_0_20230206_0908269068608694537019606.jpg","album":"Pictures"}
D/DEBUG LOG: SAVE PHOTO TO ALBUM
D/DEBUG LOG: HAS PERMISSION
D/DEBUG LOG: ___SAVE MEDIA TO ALBUM
D/SDK BUILD VERSION: 33
D/ENV LOG - ALBUM DIR: /storage/emulated/0/Android/media/com.vetcalculators.sofie/Pictures
E/Capacitor/Plugin: RuntimeException occurred
    java.lang.RuntimeException: Source file not found: /_capacitor_file_/storage/emulated/0/Android/data/com.vetcalculators.sofie/files/Pictures/DOCUMENT_SCAN_0_20230206_0908269068608694537019606.jpg, error: /_capacitor_file_/storage/emulated/0/Android/data/com.vetcalculators.sofie/files/Pictures/DOCUMENT_SCAN_0_20230206_0908269068608694537019606.jpg: open failed: ENOENT (No such file or directory)
        at com.getcapacitor.community.media.MediaPlugin.copyFile(MediaPlugin.java:317)
        at com.getcapacitor.community.media.MediaPlugin._saveMedia(MediaPlugin.java:255)
        at com.getcapacitor.community.media.MediaPlugin.savePhoto(MediaPlugin.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"55940831","pluginId":"Media","methodName":"savePhoto","success":false,"error":{"message":"RuntimeException occurred"}}
E/Capacitor/Console: File:  - Line 24 - Msg: Error: RuntimeException occurred
V/FA: Inactivity, disconnecting from the service

**Comment by nkalupahana** [comment]
@macsupport I've heard there's issues with paths with this plugin; fixing that might take a while. For now, could you change the `responseType` to `Base64`? I know for a fact that is supported by 4.0.1.

**Comment by macsupport** [comment]
I will check it out. My issue is I save the image src on a page by saving the path to localstorage. When I use base64, it slows down the process noticeably and takes a lot of localstorage memory.

**Comment by nkalupahana** [comment]
I see, okay. I'll try to get the filesystem stuff figured out, but I might not have time to take a look at it for another week or so, sorry :(

**Comment by macsupport** [comment]
Just checking in on any solution yet for this issue?

**Comment by nkalupahana** [comment]
Sorry, been really busy recently. Hopefully will have a chance to work on fixing this in the next week or so.

**Comment by nkalupahana** [comment]
@macsupport Can you try saving the image before you pass the path through `Capacitor.convertFileSrc`? The path should be a local path that starts with `file://`. I just tried this using the Camera plugin and was able to get it working.

**Comment by macsupport** [comment]
Saving the image before saving the path through `Capacitor.convertFileSrc` works in Android. 
I'm getting the error `undefined is not an object (evaluating 'albums.albums.find') `in iOS though.

**Comment by nkalupahana** [comment]
That's a JavaScript error, right? I believe that's an error in your code, since these plugins don't have any JavaScript to speak of.

**Comment by macsupport** [comment]
Oops, sorry on that!
Thanks for providing the example code, although I only see references to Android, not iOS

`if (Capacitor.getPlatform() === "android") opts["album"] = "Demo Album";`

**Comment by nkalupahana** [comment]
The example works on both Android and iOS, Android just needs that extra option.
