### ISSUE TITLE
Custom filenames

### ISSUE THREAD

**Issue by MadameMinty** [capacitor-community/media#40]
**Is your feature request related to a problem? Please describe.**
Can't `savePhoto()` with a custom filename. It forces generic `IMG_...` filename, regardless of `inputFile`.

**Describe the solution you'd like**
In `MediaPlugin.java`, replace `"IMG_" + timeStamp + extension` with `absolutePath.substring(absolutePath.lastIndexOf("/")+1)` i.e. instead of using a generic `IMG_...` filename, just use the name of the file provided as source. This could be under a conditional checking for a boolean flag `custom` passed from `savePhoto()`→`_saveMedia()`→copyFile()`.

**Describe alternatives you've considered**
Renaming the output file, but this feels like a horrible idea. I just made a fork for myself with forcing `inputFile` filename (no condition), but it'd be nice if this was in-built. This is pretty basic functionality, I'd think.

**Comment by shaifulborhan** [comment]
Would love to have this too. Thank you!

**Comment by nkalupahana** [comment]
Very fair. I think it might be best to allow any custom filename on the JS side, and let developers do a substring to use the original file's name if they want. Will work on this sometime soon!

**Comment by nkalupahana** [comment]
Added in 5.2.1.
