### ISSUE TITLE
Saving media file to IOS photo library

### ISSUE THREAD

**Issue by AssafGolani** [capacitor-community/media#44]
**Is your feature request related to a problem? Please describe.**
Hi,
First of all, it would be great if you'll add a section of "forum" besides of feature request and bug report.
My problem should be in a discussion because it's neither feature request or bug report (I think)

I use the saveVideo method, I send url (tried base64 either) and i get error when reaching the part of the swift code of saving the downloaded media file to the photo library, the !success in the completionhandler is false.
you can see the following screenshot:

<img width="1279" alt="saveVideoPhotoLibrary" src="https://user-images.githubusercontent.com/30038748/232465975-241f02b9-9064-4840-a61c-53fa7c57b01b.png">

How do you handle this issue?

Thanks

**Comment by nkalupahana** [comment]
Can you share your JavaScript code? I also recommend you [check out the examples for saving video to check yourself for any common errors.](https://github.com/capacitor-community/media/blob/master/example/src/components/SaveMedia.tsx#L65-L94)

**Comment by AssafGolani** [comment]
Hi @nkalupahana,
As recommended somewhere here before, I downloaded the file to the filesystem using capacitor-blob-writer plugin and then I passed the path of the local file to the saveVideo method
Otherwise, the url (link to the video file I get from the BE cloud) I set to the path in opts object to the saveMedia file causing the problem I mentioned.

**Comment by nkalupahana** [comment]
Again, if you'd like us to investigate this issue, please share your JavaScript code, including the URL.

**Comment by adeel399** [comment]
Hy can we get specific album media using that plugin let say i want to get all files inside instagram dolde on my iphone if yes 

Can u show me how with a bit of code if possible 
Thankz

**Comment by adeel399** [comment]
> Hy can we get specific album media using that plugin let say i want to get all files inside instagram dolde on my iphone if yes 
> 
> Can u show me how with a bit of code if possible 
> Thankz

@nkalupahana i know its not relevant with the issue above but if u can just rply here

**Comment by nkalupahana** [comment]
@adeel399 You can't get images from another app using this plugin (or any plugin for that matter). If you need additional support, please open a new issue instead of using someone else's issue.

**Comment by adeel399** [comment]
> @adeel399 You can't get images from another app using this plugin (or any plugin for that matter). If you need additional support, please open a new issue instead of using someone else's issue.

No i am talking about iphone local photos .like we get all iphone albums can we get images from specific folder using that get medias function?
