### ISSUE TITLE
I need a feature in which we can get all media files from specific folder  from ios like camera etc

### ISSUE THREAD

**Issue by adeel399** [capacitor-community/media#45]
**Is your feature request related to a problem? Please describe.**
I have an app in which i need to get all local albums from ios photos which i am able to show using this plugin but another thing which i want is to get all the media file from any spacific albums that i previously get from media plugin. 

**Describe the solution you'd like**
A method / function in which i ll add album name and able to get all files in that folder/album 

**Describe alternatives you've considered**
file plugin for android was able to do same thing but on ios i think it has some issue .. thats why i look for that plugin

**Additional context**

I also look for some apps on ios that do that so i think its possible to do ... 

Please explain if u can make that or is there any option already available in your plugin 

Thanks

**Comment by nkalupahana** [comment]
Sorry, just got back to this. I saw you asked for help in the Ionic discord -- is this still something you need help with? As you might've seen, `getMedias` has an album identifier filter, so that should work with a really high quantity.

**Comment by adeel399** [comment]
> Sorry, just got back to this. I saw you asked for help in the Ionic discord -- is this still something you need help with? As you might've seen, `getMedias` has an album identifier filter, so that should work with a really high quantity.

Yeah i still need help , as i only have album name to get spacific album details along with photos , if we can do that can u show me with code an example by passing album name .

**Comment by nkalupahana** [comment]
As mentioned in the documentation, you can get an album's identifier by its name using `getAlbums`. Something like this (untested, may have syntax errors):
```
const { albums } = await Media.getAlbums();
const album = albums.filter(album => album.name === "Album Name")[0];
const response = await Media.getMedias({
    quantity: 999999,
    albumIdentifier: album.identifier
});
```

**Comment by nkalupahana** [comment]
@adeel399 any updates?

**Comment by adeel399** [comment]
> @adeel399 any updates?

I tried

**Comment by adeel399** [comment]
> > @adeel399 any updates?
> 
> I tried 
> but get this on ios simulator  i could not get full data
> 
> `⚡️  TO JS {"medias":[{"data":"\/9j\/4AAQSkZJRgABAQAASABIAAD\/4QBMRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAAqACAAQAAAABAAABVaADAAQAAAABAAABAAAAAAD\/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+\/+ICKElDQ19QUk9GSUxFAAE
> ⚡️  [error] - ERROR {"rejection":{},"promise":{"__zone_symbol__state":0,"__zone_symbol__value":"..."},"zone":{"_parent":{"_parent":null,"_name":"<root>","_properties":{},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":0},"zone":"...","_parentDelegate":"...","_forkZS":"...","_forkDlgt":"...","_forkCurrZone":"...","_interceptZS":"...","_interceptDlgt":"...","_interceptCurrZone":"...","_invokeZS":"...","_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":"...","_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"_name":"angular","_properties":{"isAngularZone":true},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":155},"zone":"...","_parentDelegate":"...","_forkZS":"...","_forkDlgt":"...","_forkCurrZone":"...","_interceptZS":"...","_interceptDlgt":"...","_interceptCurrZone":"...","_invokeZS":{"name":"angular","properties":"..."},"_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":{"name":""},"_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"task":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","runCount":0}}`

I am stuck at this issue please help me

**Comment by nkalupahana** [comment]
@adeel399 Can you share the code you're running that gives that output?

**Comment by adeel399** [comment]
> @adeel399 Can you share the code you're running that gives that output?

this.plt.ready()
      .then(async () => {

      const { albums } = await Media.getAlbums();
      const album = albums.filter(album => album.name === "Adeel")[0];
      const response = await Media.getMedias({
          quantity: 999999,
          albumIdentifier: album.identifier
      });

           for (let i = 0; i < response.medias.length; i++) {
            this.allfolders.push({
              base64: this.allfolders[i].data,
            });
           }


Above is the code in which i am getting photos of album name Adeel and then pushing base64 into another array

**Comment by nkalupahana** [comment]
@adeel399 What is `this.allfolders[i]`? Isn't the data at `response.medias[i].data`? Based on the log you sent, it looks like image data is being sent there. Insert `console.log` statements at each step (after getting albums, after filtering albums, after getting a response) and try to understand how the data is structured.

**Comment by adeel399** [comment]
> @adeel399 What is `this.allfolders[i]`? Isn't the data at `response.medias[i].data`? Based on the log you sent, it looks like image data is being sent there. Insert `console.log` statements at each step (after getting albums, after filtering albums, after getting a response) and try to understand how the data is structured.

I am able to show images , just want to know is that show all images as well as videos?

**Comment by nkalupahana** [comment]
@adeel399 It's just images, no videos.

**Comment by adeel399** [comment]
> @adeel399 It's just images, no videos.

And what about cope or move one image to other album is tht possible

**Comment by nkalupahana** [comment]
You could copy an image to another album using `getMedias` and `saveImage`. Moving is currently not supported, though.

**Comment by adeel399** [comment]
> You could copy an image to another album using `getMedias` and `saveImage`. Moving is currently not supported, though.

Can show me like of code for that .. copying image from sepecific album and pasting to other album

**Comment by nkalupahana** [comment]
Well, you get the base64 for an image from `getMedias`, right? So you can then save that base64 string using `savePhoto`; something like:

```
Media.savePhoto({
    path: base64DataFromGetMedias,
    albumIdentifier: identifierForAlbum
})
```

You can get the album identifier the same way you got it earlier, by using getAlbums and filtering.

**Comment by adeel399** [comment]
> Well, you get the base64 for an image from `getMedias`, right? So you can then save that base64 string using `savePhoto`; something like:
> 
> ```
> Media.savePhoto({
>     path: base64DataFromGetMedias,
>     albumIdentifier: identifierForAlbum
> })
> ```
> 
> You can get the album identifier the same way you got it earlier, by using getAlbums and filtering.

Thanks alot you really help me alot, hope in future u will move feature as well .. only that thing is missing now in my project for ios

**Comment by adeel399** [comment]
> Well, you get the base64 for an image from `getMedias`, right? So you can then save that base64 string using `savePhoto`; something like:
> 
> ```
> Media.savePhoto({
>     path: base64DataFromGetMedias,
>     albumIdentifier: identifierForAlbum
> })
> ```
> 
> You can get the album identifier the same way you got it earlier, by using getAlbums and filtering.

Thanks alot you really help me alot, hope in future u will move feature as well .. only that thing is missing now in my project for ios
