### ISSUE TITLE
Capacitor 5 Migration

### ISSUE THREAD

**Issue by nkalupahana** [capacitor-community/media#46]
Quite a few breaking changes I'd like to roll out for this:

- [x] Plugin and Example Migration
- [x] Return album identifiers on Android instead of just names (solves unreported duplicate album name issue, and just general API confusion)
- [x] Remove Pictures/Movies designation from code -- it doesn't even work right now b/c of incorrect string comparison
- [x] Ensure empty albums are reported by `getAlbums` ( solves #6 )

Should be done this month!

**Comment by mike-kelly** [comment]
Thanks for your work on this plugin. I was going to try it but I have Capacitor 5 here. Do I need to downgrade to 4 in the meantime to be able to try it out?

**Comment by nkalupahana** [comment]
@mike-kelly we're now upgraded to Capacitor 5!
