### ISSUE TITLE
Capacitor V4 Android getAlbums() returns an empty array

### ISSUE THREAD

**Issue by user080975** [capacitor-community/media#48]
**Describe the bug**
On a Google Pixel 6 Capacitor V4 app and trying to get the albumIdentifier, I get an empty array without any album names. This results in the savePhoto function not working. Is this a bug or is there a way around this issue?

**To Reproduce**
1. Calling the getAlbums() results in an empty array

**Expected behavior**
Calling the getAlbums() should return a list of available albums

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 13
 - Version Capacitor V4

**Comment by nkalupahana** [comment]
Can you reproduce this with the example app? And if so, what albums do exist on your device that aren't showing up? Note that albums with no photos in them are not supported on the Capacitor v4 version of this plugin (but are on v5).

**Comment by user080975** [comment]
Oh so in V4, if there's empty albums with no photos it won't work? So we either have to inform users about this or upgrade to V5?

**Comment by nkalupahana** [comment]
@user080975 Yes, that's right, sorry. (Only on Android, though.) If you'd like, you can fork the repository and create a patched version for v4 by copying the code changes for v5.
