### ISSUE TITLE
(android) Support for API 33 / Android 13 SDK target

### ISSUE THREAD

**Issue by dpa99c** [capacitor-community/media#49]
**Describe the bug**
The Android 13/API 33 SDK makes [breaking changes](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions) to the permissions required to read/write media.

`READ_EXTERNAL_STORAGE`/`WRITE_EXTERNAL_STORAGE` permissions are no longer supported and will not be granted even if included in `AndroidManifest.xml` and requested at run-time.

The permissions `READ_MEDIA_IMAGES`/`READ_MEDIA_VIDEO`/`READ_MEDIA_AUDIO` must instead be requested.

Currently if an app containing this plugin is built using API 33 as a target and is run on a device with Android 13+, plugin methods will return an error because the plugin is [checking if `EXTERNAL_STORAGE` permissions have been granted](https://github.com/capacitor-community/media/blob/master/android/src/main/java/com/getcapacitor/community/media/MediaPlugin.java#L43).

To resolve this, the plugin will need to check the target API version and if >= 33, then check/request the `READ_MEDIA` permissions instead.

As a workaround, I have hacked [`isStoragePermissionGranted()`](https://github.com/capacitor-community/media/blob/master/android/src/main/java/com/getcapacitor/community/media/MediaPlugin.java#L143) to always return true and used [Cordova Diagnostic plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) to check/request the appropriate `READ_MEDIA` permissions before invoking this plugin

**To Reproduce**
1. Create a new app with Capacitor v5 which uses API 33 / Android 13 as target SDK
2. Add this plugin
3. Call a method from this plugin such as `Media.getAlbums()`
4. Run on Android device emulator running Android 13+
5. Observe reported error: `Unable to do file operation, user denied permission request`

**Expected behavior**
Works correctly with API 33 as target SDK

**Comment by nkalupahana** [comment]
Argh. Alright, very well, I'll try to tackle this as soon as possible. Thanks for the report.

**Comment by dpa99c** [comment]
Thanks, that was fast work 😎
