### ISSUE TITLE
Album identifier does not exist, use get Albums() to get

### ISSUE THREAD

**Issue by goforu** [capacitor-community/media#53]
I use getAlbums to find a album named "话树", unfortunately, when i savePhoto it says no exist?

```
Error: Album identifier does not exist, use getAlbums() to get
    at new CapacitorException (index.js?5d3a:85)
    at returnResult ((index):773)
    at Object.cap.fromNative ((index):755)
    at <anonymous>:1:18
```

albums 
(12) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {name: "Screenshots", identifier: "/storage/emulated/0/DCIM/Screenshots"}
1: {name: "想法", identifier: "/storage/emulated/0/Pictures/想法"}
2: {name: "百度图像搜索", identifier: "/storage/emulated/0/Pictures/graphSearch/百度图像搜索"}
3: {name: "Camera", identifier: "/storage/emulated/0/DCIM/Camera"}
4: {name: "WeiXin", identifier: "/storage/emulated/0/Pictures/WeiXin"}
5: {name: "downloads", identifier: "/storage/emulated/0/baidu/searchbox/downloads"}
6: {name: "QQ_Images", identifier: "/storage/emulated/0/Tencent/QQ_Images"}
7: {name: "QQ", identifier: "/storage/emulated/0/Pictures/QQ"}
8: {name: "Documents", identifier: "/storage/emulated/0/Documents"}
9: {name: "话树", identifier: "/storage/emulated/0/Android/media/com.chatree.chat/话树"}
10: {name: "sssss", identifier: "/storage/emulated/0/Android/media/com.chatree.chat/sssss"}
11: {name: "DCIM", identifier: "/storage/emulated/0/Android/media/com.chatree.chat/DCIM"}

**Comment by nkalupahana** [comment]
Can you share your savePhoto function call?

**Comment by nkalupahana** [comment]
@goforu following up on this. Make sure you're using the identifier, not the name. Without code I can't help further.

**Comment by goforu** [comment]
here is functions. And sometimes, getAlbumByName return nothing, thus result in error when createAlbum "album already exsits"
```javascript
import { Media } from '@capacitor-community/media'

const getAlbumByName = async (name: string) => {
  const { albums } = await Media.getAlbums()
  // console.log('albums', albums)
  return albums.find(a => a.name === name)
}

const ensureDemoAlbum = async (name: string) => {
  let album = await getAlbumByName(name)
  if (!album) {
    await Media.createAlbum({ name })
    album = await getAlbumByName(name)
  }
  if (!album) {
    throw new Error('创建了相册，但未找到！')
  }
  return album
}
export const savePhoto = async (filePath: string) => {
  const album = await ensureDemoAlbum('话树')
  return Media.savePhoto({ path: filePath, albumIdentifier: album.identifier })
}
```

**Comment by nkalupahana** [comment]
This is very strange, I'm taking a look into it. The one thing that's different that could be causing problem is the chinese text? I will attempt to reproduce it and let you know what I find.

@goforu do you have these same problems with the example app on your phone?

**Comment by nkalupahana** [comment]
Just tested, could not reproduce using the example app. Try out the example app and let me know if you have the same problems -- if you do, please share you phone model, Android version, etc.

**Comment by nkalupahana** [comment]
@goforu following up! without the information I can't help more.

**Comment by nkalupahana** [comment]
@goforu actually, I think I have a lead. I was able to reproduce the issue. When you open up the album folder in Files, does it say "There are hidden files in this folder that might include Trash"? I believe that's the issue, hopefully putting out a fix soon.

**Comment by goforu** [comment]
hello, sorry for my late reply. Yeah, I'm in China here. I will try it later. Thanks for your help! Cheers!
