### ISSUE TITLE
Permissions requested for saving are too broad

### ISSUE THREAD

**Issue by aeharding** [capacitor-community/media#55]
**Is your feature request related to a problem? Please describe.**

Calling `savePhoto` on iOS requests the user to allow access to their entire photo library, or select certain photos.

This doesn't make sense because `savePhoto` is write only.

iOS has a "Allow Photos Access: Add Photos Only" permission. This would be much more appropriate to use.

**Describe the solution you'd like**

`savePhoto` only requests/uses add photos permission.

**Describe alternatives you've considered**

N/A

**Comment by nkalupahana** [comment]
Published as v5.2.0.
