### ISSUE TITLE
Media.savePhoto's Promise<PhotoResponse> returns 'undefined' on iOS 

### ISSUE THREAD

**Issue by hughknaus** [capacitor-community/media#67]
**Describe the bug**
Version ^4.2.0 of Media plugin (have not yet moved to Capacitor 5)
Media.savePhoto's Promise<PhotoResponse> returns 'undefined' on iOS but works fine on Android.

Code snippet:
```typescript
  const photo = await Camera.getPhoto({
      ...options,
      ...customCameraOptions,
  });
  
  // Camera's photo.path is passed as 'path' to Media.savePhoto

 return await Media.savePhoto({
            path,
            album: this.platform.is('android')
                ? albumName // On Android targetAlbum will be undefined right after the creation
                : targetAlbum.identifier,
        }).then((photo) => { 
            console.log(`photos.service::savePhoto`, photo); 
            return photo 
        });
``` 

**To Reproduce**
1. Use device's native camera to take a photo
2. Pass the Camera.getPhoto... photo.path to Media.savePhoto...
3. PhotoResponse is undefined in Promise's .then((photo)

**Expected behavior**
Expected iOS to work the same as Android, PhotoResponse should be defined and provide the filePath

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: 16.5
 - Browser: Safari
 - Version ??

**Additional context**
NA

**Comment by nkalupahana** [comment]
Hi! Unfortunately, iOS doesn't work the same way as Android, so there is no "file path" that we could reference for where the photo is saved. [This is how we perform changes in a photo library](https://developer.apple.com/documentation/photokit/phphotolibrary/1620743-performchanges) -- you'll see the success message is just a Bool, no other info.

**Comment by hughknaus** [comment]
Kinda figured that might be the case... thank you for confirming.
