### ISSUE TITLE
App crash after downloading an image

### ISSUE THREAD

**Issue by beliven-francesco-delgiudice** [capacitor-community/media#70]
**Describe the bug**
The app successfully download the image but then it crashes and close the app. 
I have recently upgraded to Capacitor 5 following the guide and installed the latest version of this plugin.
The bug happens *both in emulator and real device*.

**To Reproduce**
I've attached screenshots of my code. During and after the crash there were no errors detected by both Chrome's device inspector and Android Studio.

**Package.json:**
`"dependencies": {
    "@capacitor-community/file-opener": "1.0.5",
    "@capacitor-community/media": "^5.2.2",
    "@capacitor-community/photoviewer": "^3.0.1",
    "@capacitor/android": "^5.0.0",
    "@capacitor/app": "^5.0.0",
    "@capacitor/browser": "^5.0.0",
    "@capacitor/clipboard": "^5.0.0",
    "@capacitor/core": "^5.0.0",
    "@capacitor/device": "^5.0.0",
    "@capacitor/filesystem": "^5.0.0",
    "@capacitor/ios": "^5.0.0",
    "@capacitor/share": "^5.0.0",
    "@capacitor/splash-screen": "^5.0.0",
    "@ionic-native/background-mode": "^5.31.1",
    "@ionic-native/core": "5.30.0",
    "@ionic-native/document-viewer": "5.30.0",
    "@ionic-native/file": "5.30.0",
    "@ionic-native/file-opener": "5.30.0",
    "@ionic-native/onesignal": "5.30.0",
    "@ionic/vue": "5.5.2",
    "@ionic/vue-router": "5.5.2",
    "axios": "0.21.1",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-customurlscheme-ng": "^11.0.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-doze-optimize": "^0.5.4",
    "cordova-support-android-plugin": "^1.0.2",
    "core-js": "3.8.2",
    "jetifier": "^1.6.6",
    "onesignal-cordova-plugin": "^3.2.0",
    "register-service-worker": "1.7.2",
    "vue": "3.0.5",
    "vue-router": "4.0.3",
    "vuex": "4.0.0"
  },`
  
**Attachments**
- Screen recording of the bug
- Screenshot of the JS file using the plugin
- Screenshot of the method using the function of the JS file

**Additional context**
A similar (if not the same) bug happens when using the [Photoviewer plugin](https://github.com/capacitor-community/photoviewer)

https://github.com/capacitor-community/media/assets/98807619/d5ba427f-ca54-45c1-90a4-46f1eaa48b80

<img width="709" alt="Screenshot 2023-09-15 alle 12 13 31" src="https://github.com/capacitor-community/media/assets/98807619/46c07e45-88f5-4665-8c73-66e59b58495f">
<img width="409" alt="Screenshot 2023-09-15 alle 12 10 56" src="https://github.com/capacitor-community/media/assets/98807619/c6821680-f1df-485f-a548-494f21f8897b">

**Comment by nkalupahana** [comment]
Have you set the following permissions in your AndroidManifest.xml?

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
```

If so, are you able to reproduce the same error on the example app in the `example/` folder of this repo?

**Comment by beliven-francesco-delgiudice** [comment]
Yes, I have those permissions in the android/app AndroidManifest.xml (first screenshot).

When it comes to the `example/` folder, I encountered two problems:
1. `Module not found: Error: Can't resolve '@capacitor-community/media' in '/Users/francesco.delgiudice/Downloads/media-master/example/src/components'` in the terminal (second screenshot)
2. `Caused by: org.gradle.api.resources.MissingResourceException: Could not read script '/Users/francesco.delgiudice/Downloads/media-master/example/android/capacitor-cordova-android-plugins/cordova.variables.gradle' as it does not exist.` in Android Studio (third screenshot).

Am I missing something?

<img width="716" alt="Screenshot 2023-09-18 alle 09 57 02" src="https://github.com/capacitor-community/media/assets/98807619/c017dace-e393-42fe-83d3-42ae1aad26f0">
<img width="1042" alt="Screenshot 2023-09-18 alle 10 03 36" src="https://github.com/capacitor-community/media/assets/98807619/2c11d40d-d726-4610-8ff9-a509264765c7">
<img width="1642" alt="Screenshot 2023-09-18 alle 10 05 30" src="https://github.com/capacitor-community/media/assets/98807619/9f72a799-66d4-4692-9635-ea4a259664f0">

**Comment by nkalupahana** [comment]
You need to run `npm install` in the `example/` directory first. Follow the commands in the README in that directory!

**Comment by nkalupahana** [comment]
Run `npm install` and `npm run build` in the root directory first, and then go to the example directory and run `npm install` and `ionic cap sync`.

**Comment by beliven-francesco-delgiudice** [comment]
Oh ok, I didn't know I had to build the root directory and I didn't read it in the README. 

Anyway, the `example` folder works flawlessly but as shown in the screenshot I'm using the methods in the same way so I don't understand what I am doing wrong. 

The first time I try to save it asks the user for permission and, even if granted, it doesn't save the image.
The second time it does save the image (since now it has the permissions to do it) but crashes (maybe tries to follow through and show the folder like in your `example` folder) or sometimes it doesn't crash but doesn't follow through, simply saving the image.

Do you have maybe other tips?

**Comment by nkalupahana** [comment]
`Media.createAlbum()` does not return an album object, so that part of your code might be causing issues. You have to getAlbums() after creating an album. Let me know what the behavior is after that, and share your new code, and we can go from there.

**Comment by beliven-francesco-delgiudice** [comment]
This is the code right now. It seems to be working sometimes (so a little bit better than before I guess) but the console.log aren't working so I am still confused

<img width="660" alt="Screenshot 2023-09-20 alle 11 33 06" src="https://github.com/capacitor-community/media/assets/98807619/e4d68a36-9fc7-4296-98f9-3477554bb585">

**Comment by nkalupahana** [comment]
Honestly, this code looks fine, so I'm not sure. If you can share a minimal reproducible example in a repo (minimal app with the bug), I can debug this directly. (Or if you've already fixed it, or moved on, please let me know!)

**Comment by beliven-francesco-delgiudice** [comment]
I couldn't find a bug and it still didn't work so clearly something in the configuration isn't working properly but I can't manage to find it since everything else works. At a certain point I gave up and found a different way to download the images without using a library. Thanks anyway
