### ISSUE TITLE
App is crashed on Android due to EACCES (Permission denied)

### ISSUE THREAD

**Issue by edshkliaruk** [capacitor-community/media#71]
![image](https://github.com/capacitor-community/media/assets/125352863/b268a6c8-8e05-4ed9-8bb5-ab435b780ae6)

`Caused by: java.lang.RuntimeException: Source file not found: /storage/emulated/0/Download/fd7df7f4-12ba-4a76-b687-27088727e873-1.gif, error: /storage/emulated/0/Download/fd7df7f4-12ba-4a76-b687-27088727e873-1.gif: open failed: EACCES (Permission denied)`

It's so interesting issue, because It is not reproducible all the time.

**AndroidManifest:** 
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
```

**Fragment code:**
```
private async getIdentifierAlbum() {
    const { albums } = await Media.getAlbums();

    const album = albums.find((a) => a.name === ALBUM_NAME);

    return album ? album.identifier : null;
  }

  private async downloadMediaFile(path: string, albumIdentifier: string, mediaType: MediaType) {
    let response: Maybe<Promise<PhotoResponse>> = null;
    let successMessage = '';
    let errroMessage = '';

    if (mediaType === 'image') {
      response = Media.savePhoto({
        path,
        albumIdentifier,
      });
      successMessage = 'You saved the photo';
      errroMessage = 'Failed to save the photo';
    }

    if (mediaType === 'video') {
      response = Media.saveVideo({
        path,
        albumIdentifier,
      });
      successMessage = 'You saved the video';
      errroMessage = 'Failed to save the video';
    }

    if (mediaType === 'gif') {
      response = Media.saveGif({
        path,
        albumIdentifier,
      });
      successMessage = 'You saved the gif';
      errroMessage = 'Failed to save the gif';
    }

    if (response) {
      try {
        await response;

        this.setSuccesses([
          {
            message: successMessage,
            delay: DOWNLOAD_NOTIFICATION_DELAY,
          },
        ]);
      } catch (error) {
        this.setErrors([
          {
            message: errroMessage,
            delay: DOWNLOAD_NOTIFICATION_DELAY,
          },
        ]);
      }
    }
  }

  public async downloadMediaFileToGallery(path: string, mediaType: MediaType) {
    const identifierAlbum = await this.getIdentifierAlbum();

    if (identifierAlbum) {
      await this.downloadMediaFile(path, identifierAlbum, mediaType);
      return;
    }

    await Media.createAlbum({ name: ALBUM_NAME });

    const createdIdentifierAlbum = await this.getIdentifierAlbum();

    if (createdIdentifierAlbum) {
      await this.downloadMediaFile(path, createdIdentifierAlbum, mediaType);
    }
  }
```

**Comment by nkalupahana** [comment]
Are you able to reproduce this issue at all with the example app in the `example/` folder?

Without a reproduction, I'm not sure where to go with this. The one thing I can think of though is that this is an EACESS issue on the Downloads folder. The Downloads folder is used when you're getting an image from a URL as a staging location. The image is then moved into the album and deleted from Downloads. It's possible that if you're running two downloads on the same URL in quick succession, Android is having some sort of issue with the file getting deleted and re-created. Just a thought -- feel free to provide any evidence for or against that.

**Comment by edshkliaruk** [comment]
@nkalupahana I will check this in `example` folder later and let you know what the result will be. 

I am not sure, if it's problem with Android restriction of moving and removing images. Because, it's reproducible when I open an app at the first time and try to download gif or image and I can be crashed. 

But, the interesting thing, this is crashed only with `savePhoto`, `saveGif`, `saveVideo`. getAlbum works correctly. Also I was trying to change album name, but it doesn't work.

**Comment by nkalupahana** [comment]
If it's on first open, it's likely a configuration issue, unless there's something wrong with your device specifically. Let me know what happens with the example app and we can take it from there.

**Comment by edshkliaruk** [comment]
@nkalupahana hello, I checked out `example` in https://github.com/capacitor-community/media and faced with the same issue:
<img width="1323" alt="Screenshot 2023-09-16 at 13 34 40" src="https://github.com/capacitor-community/media/assets/125352863/ad6cfb9d-6430-443b-be0a-7e885605b4fb">

**Comment by nkalupahana** [comment]
Hm, okay. Seems like an issue with your device specifically. 
* Could you share your device model and OS version?
* With the example app, does it also only crash on the first save of an image? Is that the first save of any image (and then it works for any other image), or for the first time for any image/video from the Internet?
* If you save from base64, does the error occur?

**Comment by edshkliaruk** [comment]
@nkalupahana 
Yeah of course.
1. Xiaoma Mi 11 Lite. Android version: 12 SKQ1.210908.001
2. I haven't reproduced it at once. If you download several files from internet and base64 or video, eventually it will happend.
3. I haven't tested this specific case (will do this later)
4. I have 64GB (occupied 30.3 GB)

**Comment by edshkliaruk** [comment]
Is it possible to catch an error not to crash application? if it's difficult to resolve.

**Comment by ericcch** [comment]
@edshkliaruk I have the same error, fixed it by adding android:requestLegacyExternalStorage="true" in AndroidManifest.xml

>     <application
>         android:requestLegacyExternalStorage="true"
>         android:allowBackup="true"
>         ....
>

**Comment by edshkliaruk** [comment]
@ericcch I added this param in AndroidManifest.xml but It didn't help me.

**Comment by nkalupahana** [comment]
Crash is now caught.

**Comment by edshkliaruk** [comment]
@nkalupahana thank you so much)
