### ISSUE TITLE
Is there any method to retrieve more photos like using offset in query?

### ISSUE THREAD

**Issue by rkdrnf** [capacitor-community/media#72]
**Is your feature request related to a problem? Please describe.**
I'm trying to build custom gallery to enable users to pick photos from.

**Describe the solution you'd like**
photos must be loaded constantly as users navigate through gallery so there must be a method to load more photos using cursor token or offset.
Is there any way to achieve this using this plugin?

**Comment by nkalupahana** [comment]
This is currently not supported, as far as I know -- you'll have to fetch everything at once. If this is a feature you need, feel free to implement it and make a PR -- you should be able to add a `predicate` to `PHFetchOptions` that allows for filtering by `startDate`, allowing for some sort of pagination.

**Comment by alexcroox** [comment]
I couldn't get anymore than 36 photos to load from an albumn in iOS, did anyone get around that? If we can't use offsets I'm happy to load all of them, but the plugin only returns a max of 36
