### ISSUE TITLE
Error: RuntimeException occurred : In SaveVideo method

### ISSUE THREAD

**Issue by Arun-Jain** [capacitor-community/media#75]
**Describe the bug**
Sometimes getting Error: RuntimeException occurred while downloading video to specific location in android.

**To Reproduce**
Use saveVideo method with proper opts parameters
sometimes getting this error but video downloaded in downloads
If not getting error video downloaded in specific directory given

Video downloaded in both cases but why randomly happening?

<img width="560" alt="image" src="https://github.com/capacitor-community/media/assets/16155501/6e5b4c5d-7641-40a7-8ea6-7dce6ae5e8b5">

Seems to be the copyfile function sometimes working and sometimes not working.

**Comment by nkalupahana** [comment]
Sorry for the delay. Should be fixed on 5.3.1, please confirm.
