### ISSUE TITLE
Unable to save Video - iOS 13.6 - Simulator

### ISSUE THREAD

**Issue by dotjiwa** [capacitor-community/media#8]
Hi There--

**Describe the bug**
When using the saveVideo function, I am receiving the below error. 

"message":"Unable to save video to album","errorMessage":"The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)"

I have given the app Read & Write permissions when prompted, and confirmed in the Settings.

I am following all steps in the ReadMe, and have included code and log below. Please advise. Thanks!

**To Reproduce**

Code: 

    console.log("album found!");
    console.log("album: " + JSON.stringify(this.album));
    console.log("platform : " + platform);
    console.log("photo album info : " + JSON.stringify(this.album));
    var albumOption = (platform == "ios" ? this.album.identifier : this.album.name);
    var options = { path: this.video.url, album: albumOption };
    console.log("saveVideo options : " + JSON.stringify(options));

    media
    .saveVideo(options)
    .then(console.log)
    .catch(console.log);

Log: 

  [log] - album found!
⚡️  [log] - album: {"name”:”MyAlbum”,”identifier":"A0B220CF-57D6-40F1-B2F7-CC49D88DDA95/L0/040","type":"user"}
⚡️  [log] - platform : ios
⚡️  [log] - photo album info : {"name”:”MyAlbum”,”identifier":"A0B220CF-57D6-40F1-B2F7-CC49D88DDA95/L0/040","type":"user"}
⚡️  [log] - saveVideo options : {"path":"https://s3-us-west-2.amazonaws.com/contentjaguar-hosted.com/image-hosted/11sustainablevid.mp4","album":"A0B220CF-57D6-40F1-B2F7-CC49D88DDA95/L0/040"}
⚡️  To Native ->  MediaPlugin saveVideo 117408218
ERROR MESSAGE:  {"message":"Unable to save video to album","errorMessage":"The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)"}
⚡️  [log] - {"message":"Unable to save video to album","errorMessage":"The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)"}

**Expected behavior**
Expected behavior is the video saves to the queried and found album. 

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Simulator w/ XCode
 - OS: iOS 13.6

**Comment by oconcept** [comment]
Confirmed same issue when deployed directly to my device. iPhone 7 iOS 13.6. 

I should also mention the CreateAlbum and GetAlbum functions both successfully execute on both the Simulator and my device. 

Yet the Save Video function throws the error listed in the first post above.

**Comment by oconcept** [comment]
So I have worked around this by downloading the video locally using the Capacitor FileSystem API, then sending the localUri to the saveMedia function. Once downloading locally, this function works. 

@stewwan - It would be helpful to others if the requirement of downloading locally was added to the ReadMe. Hopefully this will help someone else. Cheers!

**Comment by amakh** [comment]
@oconcept Does your code work on android too? I can see in your code that you have `
console.log("album found!");`
I'm still trying to find a work around on getAlbums returning `Album already exists` mentioned here #6

**Comment by oconcept** [comment]
Hi @amakh - I haven't tested on android yet. Reviewing the other thread, is this only an issue in the emulator for you? I saw a comment saying everything is working on a physical device, is that correct?

**Comment by amakh** [comment]
@oconcept Unfortunately it doesn't work on android either :/
Feel free to keep us updated on the other issue if you try on android 👍

**Comment by mcarnoky001** [comment]
This is my working code of saving recorded video to iphone gallery album. Video is stored in tmp folder of application.
this.state.videoUrl = "capacitor:\/\/myapp.com\/_capacitor_file_\/private\/var\/mobile\/Containers\/Data\/Application\/1F68250A-EB4B-475A-93E0-FE4F0C5C2C74\/tmp\/E97451DA-6D4E-46E1-8D4B-5ACDE0EC87F4.mp4"
write file plugin: [github](https://github.com/diachedelic/capacitor-blob-writer)

```
import {Capacitor, Plugins, FilesystemDirectory } from "@capacitor/core";
import { Media } from "@capacitor-community/media";
import { writeFile } from "capacitor-blob-writer";
const media = new Media();

saveVideo = async () => {
    if (Capacitor.isNative) {
      var convertedUrl = Capacitor.convertFileSrc(this.state.videoUrl);
      const platform = Capacitor.getPlatform();
      const albumName = "Album Name";
      let albumIdentifier = "";
      const res = await fetch(convertedUrl);
      const blob = await res.blob();
      var uri = await writeFile({
        path: "media/videos/video.mp4",
        directory: FilesystemDirectory.Data,
        data: blob,
        recursive: true,
        fallback: (err) => {
          console.log(err);
          return process.env.NODE_ENV === "production";
        },
      });
      if (platform === "ios") {
        // Handle albums
        let albums = await media.getAlbums();
        albumIdentifier =
          albums.albums.find((a) => a.name === albumName)?.identifier || null;
        console.log("album: " + albumIdentifier);

        if (!albumIdentifier) {
          console.log("Creating album");
          // Doesn't exist, create new album
          await media.createAlbum({ name: albumName });
          albums = await media.getAlbums();
          albumIdentifier = albums.albums.find((a) => a.name === albumName)
            ?.identifier;
        }
      } else if (platform === "android") {
        await media.createAlbum({ name: albumName });
      }
      media
        .saveVideo({
          path: uri.uri,
          album: platform === "ios" ? albumIdentifier : albumName,
        })
        .then((r) => console.log(r))
        .catch((e) => console.error(e));
    }
  };
```

**Comment by mepc36** [comment]
> This is my working code of saving recorded video to iphone gallery album. Video is stored in tmp folder of application.
> this.state.videoUrl = "capacitor://myapp.com/_capacitor_file_/private/var/mobile/Containers/Data/Application/1F68250A-EB4B-475A-93E0-FE4F0C5C2C74/tmp/E97451DA-6D4E-46E1-8D4B-5ACDE0EC87F4.mp4"
> write file plugin: [github](https://github.com/diachedelic/capacitor-blob-writer)
> 
> ```
> import {Capacitor, Plugins, FilesystemDirectory } from "@capacitor/core";
> import { Media } from "@capacitor-community/media";
> import { writeFile } from "capacitor-blob-writer";
> const media = new Media();
> 
> saveVideo = async () => {
>     if (Capacitor.isNative) {
>       var convertedUrl = Capacitor.convertFileSrc(this.state.videoUrl);
>       const platform = Capacitor.getPlatform();
>       const albumName = "Album Name";
>       let albumIdentifier = "";
>       const res = await fetch(convertedUrl);
>       const blob = await res.blob();
>       var uri = await writeFile({
>         path: "media/videos/video.mp4",
>         directory: FilesystemDirectory.Data,
>         data: blob,
>         recursive: true,
>         fallback: (err) => {
>           console.log(err);
>           return process.env.NODE_ENV === "production";
>         },
>       });
>       if (platform === "ios") {
>         // Handle albums
>         let albums = await media.getAlbums();
>         albumIdentifier =
>           albums.albums.find((a) => a.name === albumName)?.identifier || null;
>         console.log("album: " + albumIdentifier);
> 
>         if (!albumIdentifier) {
>           console.log("Creating album");
>           // Doesn't exist, create new album
>           await media.createAlbum({ name: albumName });
>           albums = await media.getAlbums();
>           albumIdentifier = albums.albums.find((a) => a.name === albumName)
>             ?.identifier;
>         }
>       } else if (platform === "android") {
>         await media.createAlbum({ name: albumName });
>       }
>       media
>         .saveVideo({
>           path: uri.uri,
>           album: platform === "ios" ? albumIdentifier : albumName,
>         })
>         .then((r) => console.log(r))
>         .catch((e) => console.error(e));
>     }
>   };
> ```

Hey @mcarnoky001, I am trying to save a video from a URL to an iphone's local photo roll. Would you mind please sharing the part of your code that accomplishes this?

Apologies if you've already referenced that code here, but I'm basically wondering how you generate this path:

`this.state.videoUrl = "capacitor://myapp.com/capacitor_file/private/var/mobile/Containers/Data/Application/1F68250A-EB4B-475A-93E0-FE4F0C5C2C74/tmp/E97451DA-6D4E-46E1-8D4B-5ACDE0EC87F4.mp4"`

Thanks!

Are you just using the `capacitor-blob-writer` package to save the video to local photo roll?

**Comment by mcarnoky001** [comment]
@mepc36  Im using a plugin, which returns the given path. https://github.com/TeamHive/capacitor-video-recorder
