### ISSUE TITLE
feat(ios): support jpeg files instead of png

### ISSUE THREAD

**Issue by stephan-fischer** [capacitor-community/media#80]
Currently the plugin saves only *.png files on iOS Devices for compatibility. But SDWebImage allows jpegs, and i suggest to save .jpg files.

**Comment by nkalupahana** [comment]
@stephan-fischer what's your use case for saving images as JPEGs instead of PNGs? As far as I understand, PNGs should support pretty much all JPEG features (and much more).

**Comment by stephan-fischer** [comment]
@nkalupahana but the filesize is huge, especially for large images. For example i have a app to access images from the cloud  (Amazon Photos etc), the original jpeg filesize is 1,83 MB - after a download the file is a png with 21 mb. - or is it better to have a function saveFile() <- it auto detects format like jpg, png, gif and saves the file as it is?

**Comment by stephan-fischer** [comment]
I think the cordova plugin photo-library can save jpegs as well:
[Photo-Library](https://github.com/terikon/cordova-plugin-photo-library/blob/master/src/ios/PhotoLibraryService.swift)
