### ISSUE TITLE
MediaFetchOptions support individual photo for high resolution

### ISSUE THREAD

**Issue by alexcroox** [capacitor-community/media#84]
I'm currently using generating a gallery for a user to pick a photo from:

```
const { medias: getMedias } = await Media.getMedias({
        albumIdentifier: recentlyAddedAlbum.identifier,
        thumbnailWidth: 500,
        thumbnailQuality: 70,
        sort: [
          {
            key: 'creationDate',
            ascending: false
          }
        ],
        quantity: 100
      })
```

I'm selecting a small thumbnail size so the list is more memory effecient when scrolling.

I'd like when the user selects a photo to grab the full resolution version of the image, something like this:

```
const { medias } = await Media.getMedias({
  identifier: selectedMediaIdentifier
})

const highResolutionPhoto = medias[0]
```

**Comment by nkalupahana** [comment]
Instead of adding this to `getMedias`, I've added a `getMediaByIdentifier` function to v6.0.0. Let me know how it works for you. A sample implementation of it is in the example app.

**Comment by alexcroox** [comment]
Thank you! 🤩
