### ISSUE TITLE
feat(ios): get specific media by identifier

### ISSUE THREAD

**Issue by maximilien0405** [capacitor-community/media#85]
Hello there, first of all thanks for maintaining the plugin. I'm planning on making a way for my users to send images&videos in the same way as any social media app does it. By fetching an array of images from the different albums. However as i just saw this is not yet supported by android.. wich means that i can't use it because what's the point of doing something only on IOS :(

Any plans to implement it one day ? If not is there any other plugin that does that and that is actively maintained ? Thanks ! @nkalupahana

**Comment by nkalupahana** [comment]
Hi! Unfortunately, this is not currently supported through the plugin -- but that's because you don't need a third party plugin to get images on Android! When you call `getAlbums()` on Android, you'll get a file path to the album (the identifier). You can then use the built-in Capacitor `Filesystem` plugin to get the images out of the album (folder).

**Comment by maximilien0405** [comment]
Oh ! Okay great i will try that then :) thanks for the info

**Comment by maximilien0405** [comment]
Hi, i'm working on that feature right now. However the capacitor Filesystem plugin only allows me to get a directory if i provide the path. I saw that there is a getAlbumPath() function on this plugin, but it's not avaiable on IOS. Is there another way to get the path on IOS ? I don't want to use the getMedias() function for IOS because i need the videos too.. :p @nkalupahana

**Comment by maximilien0405** [comment]
Hi, i'm working on that feature right now. However the capacitor Filesystem plugin only allows me to get a directory if i provide the path. I saw that there is a getAlbumPath() function on this plugin, but it's not avaiable on IOS. Is there another way to get the path on IOS ? I don't want to use the getMedias() function for IOS because i need the videos too.. :p @nkalupahana

**Comment by nkalupahana** [comment]
@maximilien0405 images aren't stored at a path on iOS, which is why that function isn't available on iOS. Let me see if we can change getMedias to return videos.

**Comment by maximilien0405** [comment]
Okay thanks ! It would be cool ! Also i just saw the documentation, it would be also great to have a way to get images from an X index to X other index ? Because as i understand, right now there is only a "quantity" option settings, but if i'm trying to get the first 100 images, then the next 100 ones to avoid loading them all, then it's not possible :/
Basically i'm trying to recreate the same modal to pick images/videos as the Discord one one mobile @nkalupahana

**Comment by nkalupahana** [comment]
1. I've added functionality to give video thumbnails along with photo thumbnails via `getMedias()` -- should be released soon.
2. Just increase the quantity from 100 to 200 to paginate -- the OS should cache the first 100, so there shouldn't be too much of a performance hit, and you can just display images 100 - 200.
3. Unfortunately, I don't currently have the time to implement something that can get a full-sized image or video from the photo library. I would recommend using a Capacitor image/video picker plugin that already exists: for example, https://github.com/capawesome-team/capacitor-plugins/tree/main/packages/file-picker. If anyone wants to implement this, I think the best thing to do would be to create a function on iOS that takes the media identifier and returns a filesystem URL, so it can be manipulated the same way as the Android media identifiers.

**Comment by maximilien0405** [comment]
@nkalupahana Hi, just wanted to tell you i oppened a pull request and tried to implement a function to get the path of a media in IOS, it's right there -> #88

**Comment by nkalupahana** [comment]
I've added a `getMediaByIdentifier` function to v6.0.0. Let me know how it works for you. A sample implementation of it is in the example app.
