### ISSUE TITLE
feat: Capacitor 6 Support

### ISSUE THREAD

**Issue by ckoon-infopro** [capacitor-community/media#89]
Capacitor 6.0 has been announced, bringing support for Android 14 and iOS 17.
[https://ionic.io/blog/announcing-capacitor-6-0](https://ionic.io/blog/announcing-capacitor-6-0)

Updating Plugins to 6.0:
[https://capacitorjs.com/docs/updating/plugins/6-0](https://capacitorjs.com/docs/updating/plugins/6-0)

**Comment by rickkidskonnect** [comment]
Do you have any time indication? Sorry for nagging

**Comment by nkalupahana** [comment]
Within the next two weeks.

**Comment by nkalupahana** [comment]
Published!
