### ISSUE TITLE
Get Videos

### ISSUE THREAD

**Issue by calls9-mattwyld** [capacitor-community/media#9]
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be a way yet to get video's in capacitor. There is the `getPhoto()` method in the capacitor camera plugin but no `getVideo()`. Even if it just returns a file URL, this would be super useful.

**Describe the solution you'd like**
A `getVideos()` method that opens the OS Videos to be able to select a video and it return the video in say blob format or the file location 

**Describe alternatives you've considered**
I have used to Cordova camera plugin to achieve this however there are some issues when building it in android.

**Additional context**
I can provide more details upon request, hopefully the above makes sense.

**Comment by stewones** [comment]
as stated by @imhoffd, this functionality doesn't make sense in here, this plugin only aims to manipulate medias on user's device whereas we aren't able to do with official capacitor packages. ie filesystem
