### ISSUE TITLE
Photo Gallery Sync 

### ISSUE THREAD

**Issue by shawnweiland** [capacitor-community/media#94]
Been reading through the documentation and haven't found a good way to sync an entire media gallery using the plugin. Can "quantity" be overriden to batch save a discrete index of images and move to the next index. Trying to run Medias as a background task that can be toggled on/off via user controls.

**Comment by nkalupahana** [comment]
Unfortunately, not sure it can -- I haven't seen an offset parameter anywhere in the Swift documentation (although I might be wrong). Your best bet is probably to order the images by recency in `getMedias()`, and then store the last identifier synced or something like that. Then, you can see any new identifiers and just grab those.
