### ISSUE TITLE
getting this warning not implemented followed all guide

### ISSUE THREAD

**Issue by xalteropsx** [capacitor-community/media#96]
![image](https://github.com/user-attachments/assets/46c47c87-f7f8-4e2f-bde0-ab76bd319bb5)

also how do u call pagination number ? 

suppose if request an media i want a paginate number 0-10 then 10-20 

in quanity props u have only show number does it support   this symbol (-)

**Comment by nkalupahana** [comment]
As described in the documentation, `getMedias` is only available on iOS. On Android, you can get images by passing your album identifier, which is a filesystem path, to the filesystem plugin.

There's no native functionality for pagination on iOS (i.e. as far as I know the Swift API for it doesn't support it so the plugin can't provide it), so if you want 10-20, you'll need to request 0-20 and then extract the last 10. As long as you've requested 0-10 first though, iOS will cache them, so the performance for getting 0 - 20 after getting 0-10 should be the same as getting 0-10.

**Comment by nkalupahana** [comment]
@mssoliveira instead of replying to a closed issue (which emails unrelated users and isn't easily visible to maintainers on GitHub since the issue is marked as closed), please open a separate issue with your code and more details about your problem and we can take a look :)
